### PR TITLE
Fixed STONWriter>>encodeCharacter: to not escaping single quotes in JSON mode

### PR DESCRIPTION
**Pull request by mumez**
Fix of the issue: https://github.com/GsDevKit/ston/issues/18

Now `STON toJsonString: 'steve''s job'` is encoded correctly.

2023-06-28 10_20_10-localhost_3390 - リモート デスクトップ接続

### CODE REVIEW

**Comment by dalehenrich** [comment]
@mumez, It looks the [two new unit tests are failing](https://github.com/GsDevKit/ston/actions/runs/5396223909/jobs/9815687451?pr=19#step:4:7678)

**Comment by mumez** [comment]
OK I'll investigate the failed tests. Maybe test assertion code should be fixed also.

**Comment by mumez** [comment]
I found that STONWriterTests>>testDoubleQuoteString (and its overrides) need to be fixed also.
They original assertion string was '"\"\''\\\t\r\n\f\b"', but it should be '"\"''\\/\t\r\n\f\b"'.

**Comment by mumez** [comment]
- I forgot to fix STON091Writer>>encodeCharacter:, STONUtf8Writer>>encodeCharacter: - now they are fixed.
- Also I added $/ character to test cases (that was added in Pharo version)

**Comment by dalehenrich** [comment]
@mumez, looks great the "Post Workflow" action posts a notification to slack on one of my channels, so the fix is good to go ... THANKS!

**Pull request merged**
